"""Download the VPS HR .env (secrets for Telegram CLI) into tests/tg_cli.env.
Strips to only the fields the CLI needs + normalizes the private key to a
single \\n-escaped line so the .env loader can parse it."""
import paramiko

c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect("187.77.114.168", username="dev", password="password", timeout=30)
_, out, _ = c.exec_command("cat /home/dev/ykp/ykp-hr-v1/.env")
src = out.read().decode()

keep = {
    "GOOGLE_SERVICE_ACCOUNT_EMAIL",
    "YKP_HR_SPREADSHEET_ID",
    "TELEGRAM_WEBHOOK_SECRET",
    "CRON_SECRET",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
}
# Also pull the private key (multi-line) and re-escape to single line.
lines = src.splitlines()
pk_lines = []
in_pk = False
other = {}
for line in lines:
    if line.startswith("GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY="):
        # may be single-line already
        val = line.split("=", 1)[1].strip().strip('"')
        if "BEGIN PRIVATE KEY" in val and "END PRIVATE KEY" in val:
            other["GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY"] = val
            continue
        # multi-line: start capturing
        in_pk = True
        pk_lines.append(val)
        continue
    if in_pk:
        if "END PRIVATE KEY" in line:
            pk_lines.append(line.rstrip().rstrip('"'))
            in_pk = False
            other["GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY"] = "\n".join(pk_lines)
            pk_lines = []
        else:
            pk_lines.append(line)
        continue
    if "=" in line:
        k = line.split("=", 1)[0].strip()
        if k in keep:
            other[k] = line.split("=", 1)[1].strip().strip('"').strip("'")

# normalize private key newlines to literal \n for the .env file
pk = other.get("GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY", "")
pk_normalized = pk.replace("\r\n", "\n").replace("\n", "\\n")
other["GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY"] = pk_normalized

# also add finance + warehouse + investor spreadsheet ids if present in their envs
for app, envpath in [
    ("ykp-finance-v1", "/home/dev/ykp/ykp-finance-v1/.env"),
    ("ykp-warehouse-v1", "/home/dev/ykp/ykp-warehouse-v1/.env"),
    ("ykp-investor-v1", "/home/dev/ykp/ykp-investor-v1/.env"),
]:
    _, o2, _ = c.exec_command(f"cat {envpath}")
    s2 = o2.read().decode()
    for line in s2.splitlines():
        if "SPREADSHEET_ID" in line and "=" in line:
            k = line.split("=", 1)[0].strip()
            v = line.split("=", 1)[1].strip().strip('"').strip("'")
            other[k] = v

with open("tests/tg_cli.env", "w", encoding="utf-8") as f:
    f.write("# Auto-generated by tests/fetch_cli_env.py — secrets for tg_cli.py.\n")
    f.write("# Do NOT commit. Sourced from VPS HR .env.\n")
    for k, v in other.items():
        f.write(f"{k}={v}\n")
print("wrote tests/tg_cli.env with keys:", list(other.keys()))
c.close()