/**
 * Receiver for HR → Finance payroll notifications (MOM 1 Sep 2026 Tahap 3).
 *
 * HR calls this right after generate (FINANCE_NOTIFY_URL) so Finance knows a
 * Ready-to-Pay period is waiting. Authenticated ONLY by the shared
 * `x-finance-secret` header (HR has no Finance session cookie).
 * Write-light: records an audit entry, never touches HR data (Finance reads
 * HR payroll via its own read-only bridge).
 */
import { logAudit } from '@/lib/audit';
import { safeEqual } from '@/lib/cron';
import { handler, badRequest, unauthorized, ok } from '@/lib/http';
import { z } from 'zod';

const schema = z.object({
  period: z.string().regex(/^\d{4}-\d{2}$/),
  created: z.number().int().min(0).default(0),
  updated: z.number().int().min(0).default(0),
  skipped: z.number().int().min(0).default(0),
  generated_by: z.string().default('')
});

function hrSecretValid(req: Request): boolean {
  const secret = (process.env.FINANCE_NOTIFY_SECRET ?? process.env.HR_NOTIFY_SECRET ?? '').trim();
  if (!secret) return false;
  const presented = (req.headers.get('x-finance-secret') ?? '').trim();
  if (!presented) return false;
  return safeEqual(presented, secret);
}

export const POST = handler(async (req) => {
  if (!hrSecretValid(req)) return unauthorized('Invalid or missing x-finance-secret');
  const body = await req.json().catch(() => null);
  const parsed = schema.safeParse(body);
  if (!parsed.success) return badRequest(parsed.error.issues[0]?.message ?? 'Invalid request');

  await logAudit({
    module: 'payroll',
    action: 'hr_notify_ready',
    recordType: 'payroll_period',
    recordId: parsed.data.period,
    beforeValue: '',
    afterValue: `${parsed.data.created} created, ${parsed.data.updated} updated, ${parsed.data.skipped} skipped`,
    reason: parsed.data.generated_by ? `generated by ${parsed.data.generated_by}` : '',
    userId: 'hr-app'
  });
  return ok({ period: parsed.data.period, received: true });
});
