import {
  pgTable,
  pgEnum,
  text,
  boolean,
  timestamp,
  date,
  jsonb,
  bigserial,
  uniqueConstraint,
} from "drizzle-orm/pg-core";

// ============================================================
// Enums
// ============================================================

export const alertLevelEnum = pgEnum("hermez_alert_level", [
  "green",
  "yellow",
  "red",
]);

export const alertTypeEnum = pgEnum("hermez_alert_type", [
  "late_staff",
  "cash_diff",
  "supplier_overdue",
  "petty_cash_anomaly",
  "high_expense",
  "schema_mismatch",
  "data_missing",
]);

export const alertSeverityEnum = pgEnum("hermez_alert_severity", [
  "warning",
  "critical",
]);

export const alertSourceAppEnum = pgEnum("hermez_alert_source_app", [
  "hr",
  "finance",
  "ops",
]);

export const alertStatusEnum = pgEnum("hermez_alert_status", [
  "open",
  "ack",
  "resolved",
]);

// ============================================================
// hermez_daily_brief
// brief_id is generated by the app layer following HZBR-YYYYMMDD
// (one brief per date; the date column enforces uniqueness).
// ============================================================

export const hermezDailyBrief = pgTable("hermez_daily_brief", {
  briefId: text("brief_id").primaryKey(),
  date: date("date", { mode: "date" }).notNull().unique(),
  generatedAt: timestamp("generated_at", { mode: "date" }).defaultNow().notNull(),
  briefText: text("brief_text").notNull(),
  alertLevel: alertLevelEnum("alert_level").notNull(),
  sentToOwner: boolean("sent_to_owner").notNull().default(false),
  sentAt: timestamp("sent_at", { mode: "date" }),
});

// ============================================================
// hermez_alert_log
// alert_id is generated by the app layer following HZAL-YYYYMMDD-NNN.
// ============================================================

export const hermezAlertLog = pgTable(
  "hermez_alert_log",
  {
    alertId: text("alert_id").primaryKey(),
    date: date("date", { mode: "date" }).notNull(),
    brand: text("brand"),
    outlet: text("outlet"),
    alertType: alertTypeEnum("alert_type").notNull(),
    severity: alertSeverityEnum("severity").notNull(),
    message: text("message").notNull(),
    sourceApp: alertSourceAppEnum("source_app").notNull(),
    status: alertStatusEnum("status").notNull().default("open"),
    actionTaken: text("action_taken").notNull().default("none"),
    assignedTo: text("assigned_to"),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
    resolvedAt: timestamp("resolved_at", { mode: "date" }),
  },
  (t) => ({
    // Defect Z5 fix: unique by (date, outlet, alert_type) so the daily
    // brief can upsert a single alert row per day/outlet/type instead of
    // creating duplicates.
    dateOutletTypeUnique: uniqueConstraint("hermez_alert_date_outlet_type_unique").on(t.date, t.outlet, t.alertType),
  }),
);

// ============================================================
// hermez_config (singleton-ish key/value store)
// ============================================================

export const hermezConfig = pgTable("hermez_config", {
  configId: text("config_id").primaryKey(),
  key: text("key").notNull().unique(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow().notNull(),
  updatedBy: text("updated_by"),
});

// ============================================================
// Inferred types
// ============================================================

export type HermezDailyBrief = typeof hermezDailyBrief.$inferSelect;
export type NewHermezDailyBrief = typeof hermezDailyBrief.$inferInsert;
export type HermezAlertLog = typeof hermezAlertLog.$inferSelect;
export type NewHermezAlertLog = typeof hermezAlertLog.$inferInsert;
export type HermezConfig = typeof hermezConfig.$inferSelect;
export type NewHermezConfig = typeof hermezConfig.$inferInsert;

// ============================================================
// hermez_audit_log — per-domain audit trail for Hermez brief
// generation, alert acknowledgements, and telegram deliveries.
// ============================================================

export const hermezAuditLog = pgTable("audit_log", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  actor: text("actor").notNull(),
  action: text("action").notNull(),
  entity: text("entity").notNull(),
  entityId: text("entity_id").notNull(),
  before: jsonb("before"),
  after: jsonb("after"),
  reason: text("reason"),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
});

export type HermezAuditLog = typeof hermezAuditLog.$inferSelect;
export type NewHermezAuditLog = typeof hermezAuditLog.$inferInsert;