import {
  pgSchema,
  text,
  boolean,
  timestamp,
  date,
  jsonb,
  bigserial,
  integer,
  unique,
} from "drizzle-orm/pg-core";

const hermez = pgSchema("hermez");

// ============================================================
// Enums
// ============================================================

export const alertLevelEnum = hermez.enum("hermez_alert_level", [
  "green",
  "yellow",
  "red",
]);

export const alertTypeEnum = hermez.enum("hermez_alert_type", [
  "late_staff",
  "cash_diff",
  "supplier_overdue",
  "petty_cash_anomaly",
  "high_expense",
  "schema_mismatch",
  "data_missing",
  // Operational V1 feeds
  "ops_incident_spike",
  "ops_waste_high",
  "ops_over_sla",
]);

export const alertSeverityEnum = hermez.enum("hermez_alert_severity", [
  "warning",
  "critical",
]);

export const alertSourceAppEnum = hermez.enum("hermez_alert_source_app", [
  "hr",
  "finance",
  "ops",
]);

export const alertStatusEnum = hermez.enum("hermez_alert_status", [
  "open",
  "ack",
  "resolved",
]);

// ============================================================
// hermez_daily_brief
// brief_id is generated by the app layer following HZBR-YYYYMMDD
// (one brief per date; the date column enforces uniqueness).
// ============================================================

export const hermezDailyBrief = hermez.table("hermez_daily_brief", {
  briefId: text("brief_id").primaryKey(),
  date: date("date", { mode: "date" }).notNull().unique(),
  generatedAt: timestamp("generated_at", { mode: "date" }).defaultNow().notNull(),
  briefText: text("brief_text").notNull(),
  alertLevel: alertLevelEnum("alert_level").notNull(),
  sentToOwner: boolean("sent_to_owner").notNull().default(false),
  sentAt: timestamp("sent_at", { mode: "date" }),
  /** Deployment tag: DEMO | TESTING | PRODUCTION. */
  environment: text("environment").notNull().default("PRODUCTION"),
});

// ============================================================
// hermez_alert_log
// alert_id is generated by the app layer following HZAL-YYYYMMDD-NNN.
// ============================================================

export const hermezAlertLog = hermez.table(
  "hermez_alert_log",
  {
    alertId: text("alert_id").primaryKey(),
    date: date("date", { mode: "date" }).notNull(),
    brand: text("brand"),
    outlet: text("outlet"),
    alertType: alertTypeEnum("alert_type").notNull(),
    severity: alertSeverityEnum("severity").notNull(),
    message: text("message").notNull(),
    sourceApp: alertSourceAppEnum("source_app").notNull(),
    status: alertStatusEnum("status").notNull().default("open"),
    actionTaken: text("action_taken").notNull().default("none"),
    assignedTo: text("assigned_to"),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
    resolvedAt: timestamp("resolved_at", { mode: "date" }),
    /** Deployment tag: DEMO | TESTING | PRODUCTION. */
    environment: text("environment").notNull().default("PRODUCTION"),
  },
  (t) => ({
    // Defect Z5 fix: unique by (date, outlet, alert_type) so the daily
    // brief can upsert a single alert row per day/outlet/type instead of
    // creating duplicates.
    dateOutletTypeUnique: unique("hermez_alert_date_outlet_type_unique").on(t.date, t.outlet, t.alertType),
  }),
);

// ============================================================
// hermez_telegram_log
// Delivery audit for every outbound Telegram message (brief/alert/test).
// log_id is generated by the app layer (HZTG-… or uuid).
// ============================================================

export const hermezTelegramLog = hermez.table("hermez_telegram_log", {
  logId: text("log_id").primaryKey(),
  /** Telegram API message_id on success; null/empty on failure. */
  messageId: text("message_id"),
  /** chat_id or channel identifier the message was addressed to. */
  recipient: text("recipient").notNull(),
  /** Logical channel: owner | group. */
  channel: text("channel").notNull().default("owner"),
  /** Delivery outcome: sent | failed | retry. */
  status: text("status").notNull(),
  sentAt: timestamp("sent_at", { mode: "date" }).defaultNow().notNull(),
  errorMessage: text("error_message"),
  retryCount: integer("retry_count").notNull().default(0),
});

// ============================================================
// hermez_config (singleton-ish key/value store)
// ============================================================

export const hermezConfig = hermez.table("hermez_config", {
  configId: text("config_id").primaryKey(),
  key: text("key").notNull().unique(),
  value: text("value").notNull(),
  label: text("label"),
  unit: text("unit"),
  severity: text("severity").notNull().default("warning"),
  description: text("description"),
  isActive: boolean("is_active").notNull().default(true),
  updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow().notNull(),
  updatedBy: text("updated_by"),
});

// ============================================================
// Inferred types
// ============================================================

export type HermezDailyBrief = typeof hermezDailyBrief.$inferSelect;
export type NewHermezDailyBrief = typeof hermezDailyBrief.$inferInsert;
export type HermezAlertLog = typeof hermezAlertLog.$inferSelect;
export type NewHermezAlertLog = typeof hermezAlertLog.$inferInsert;
export type HermezTelegramLog = typeof hermezTelegramLog.$inferSelect;
export type NewHermezTelegramLog = typeof hermezTelegramLog.$inferInsert;
export type HermezConfig = typeof hermezConfig.$inferSelect;
export type NewHermezConfig = typeof hermezConfig.$inferInsert;

// ============================================================
// hermez_audit_log — per-domain audit trail for Hermez brief
// generation, alert acknowledgements, and telegram deliveries.
// ============================================================

export const hermezAuditLog = hermez.table("audit_log", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  actor: text("actor").notNull(),
  action: text("action").notNull(),
  entity: text("entity").notNull(),
  entityId: text("entity_id").notNull(),
  before: jsonb("before"),
  after: jsonb("after"),
  reason: text("reason"),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
});

export type HermezAuditLog = typeof hermezAuditLog.$inferSelect;
export type NewHermezAuditLog = typeof hermezAuditLog.$inferInsert;

// ============================================================
// Enums for action tracker
// ============================================================

export const actionPriorityEnum = hermez.enum("hermez_action_priority", [
  "LOW",
  "MEDIUM",
  "HIGH",
  "CRITICAL",
]);

export const actionStatusEnum = hermez.enum("hermez_action_status", [
  "OPEN",
  "IN_PROGRESS",
  "WAITING_APPROVAL",
  "DONE",
  "CANCELLED",
  "OVERDUE",
]);

// ============================================================
// hermez_action_tracker
// action_id is generated by the app layer following HZAC-YYYYMMDD-NNN.
// ============================================================

export const hermezActionTracker = hermez.table("hermez_action_tracker", {
  actionId: text("action_id").primaryKey(),
  sourceAlertId: text("source_alert_id"),
  title: text("title").notNull(),
  brand: text("brand"),
  outlet: text("outlet"),
  assignedTo: text("assigned_to"),
  priority: actionPriorityEnum("priority").notNull().default("MEDIUM"),
  dueDate: date("due_date", { mode: "date" }),
  status: actionStatusEnum("status").notNull().default("OPEN"),
  actionTaken: text("action_taken"),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  completedAt: timestamp("completed_at", { mode: "date" }),
});

// ============================================================
// Inferred types (action tracker)
// ============================================================

export type HermezActionTracker = typeof hermezActionTracker.$inferSelect;
export type NewHermezActionTracker = typeof hermezActionTracker.$inferInsert;